### PR TITLE
[WiP] Use script/command file to call nusmv

### PR DESCRIPTION
**Pull request by norro**
Currently, the AG analyzer calls `nusmv` directly with/on the smv file. This PR introduces a new `AGCmdAnalyzer` (and factory) that calls nusmv with `nusmv -source {sourcefile}` as this will provide a more powerful handle on the nusmv behavior.

In a first implementation stage I _changed_ the current `AGAnalyzer`. In the current implementation stage this PR introduces an _additional_ one, the new `AGCmdAnalyzer`. I did that because the new behavior introduces a fairly strict constraint, i.e. that a source file with a corresponding name has to always be present next to the smv file in order for the analysis to work.

There are a lot of alternatives to implementation of a this new `AGCmdAnalyzer`, e.g., changing the default behavior of the existing one (what I initially did, probably not a good idea), or introducing an additional option to the existing `AGAnalyzer`, or changing the `AGAnalyzer` so that it only uses the source/command file iff it exists.
Dan, what do you think?

### CODE REVIEW

**Comment by danielratiu** [comment]
I think that extending the existing AGAnalyzer to run with a source if present is the easiest. So, your proposal:
"AGAnalyzer so that it only uses the source/command file iff it exists." would be the choice.

We can use a "message.info" to inform the user about the stratefy used by the analyzer.

**Comment by danielratiu** [comment]
I would propose the following steps:

1) in the "com.mbeddr.formal.nusmv.cbd" language we add a new concept that extends NuSMVCommand (from "com.mbeddr.formal.nusmv.source") called "analyze architecture" that will generate a "read_model -i  node.system.name + "___flattenedSystem.smv" " command. If "AnalyzeArchitecture" is present in a source file, then a checking rule will disallow "read model" in that source to prevent confusion
2) we extend the AGAnalyzer logic to
    I) look if there is a source root node defined in the model that references the assembly (AnalyzeArchitecture) on which the AGAnalyzer is started
3) add a small unit test about this :-)

   II) if yes, then start "nusmv --source", if not, use the existing implementation

**Comment by norro** [comment]
@danielratiu can you please have a look at this PR? This should now be doing what you suggested. I can see in my use cases that it is doing exactly what I want from it.

1. First of all sorry for the huge PR. I had quite some trouble to get the build running and when fixing things, I had to remove lots of superfluous language dependencies and add lots of missing (extends) dependencies. This unfortunately touches lots of files. :/
1. Can you also have a look at the tests? Tests have been very flaky for me, but it seemed to be due to Java / test environment errors, not the tests themselves. I think so because of the errors I see and because larger parts of the tests in master are also failing for me.

Regarding 1.: Feel free to squash and/or cherry-pick once this PR is ready, to only take the _real_ changes. This should be the cbd language (structure, editor, typesystem, textgen), nusmv cbd tests, and the nusmv tool runner.

**Comment by danielratiu** [comment]
@norro I have cherry-picked two commits + did some cleanup.

The result is on master, please have a look if it works for you. 

Thank you for the contribution! I am closing now this PR.

**Comment by norro** [comment]
Works like a charm. Thank you!

**Pull request closed without merging**
