### PR TITLE
WiP: Add safety languages (gsn, req, ...) to gradle build

### PR DESCRIPTION
**Pull request by norro**
Do not merge, yet! Up to now, this PR is not meaningful and just to test building PRs on itemis nexus.

### CODE REVIEW

**Comment by norro** [comment]
Seems to be working, this pull request is being built on itemis nexus:
https://build.mbeddr.com/viewType.html?buildTypeId=Mbeddr2_Mbeddr_Gradle_Fasten_Build&branch_Mbeddr2_Mbeddr_Gradle_Fasten=pull%2F23&tab=buildTypeStatusDiv

I will now start working in the source branch.

**Comment by danielratiu** [comment]
LGTM

**Comment by norro** [comment]
@danielratiu Can you please undo this merge?
The Pull Request was still work-in-progress (WiP) and currently breaks the build (and therefore because of the merge master is broken).

**Comment by danielratiu** [comment]
reverted ...

**Pull request merged**
